### ISSUE TITLE
Site Not working

### ISSUE THREAD

**Issue by prajankya** [yodasco/graphub#1]
The javascript console output is

From the file
http://graphub.yodas.com/c94bbd6afadf69c81de90270364906afdea7ff25.js?meteor_js_resource=true

> Exception in delivering result of invoking 'getAllShortestPaths': TypeError: Cannot read property 'graph' of undefined
>     at t.render (http://graphub.yodas.com/c94bbd6afadf69c81de90270364906afdea7ff25.js?meteor_js_resource=true:202:694)
>     at d._renderValidatedComponentWithoutOwnerOrContext (http://graphub.yodas.com/c94bbd6afadf69c81de90270364906afdea7ff25.js?meteor_js_resource=true:120:10702)
>     at d._renderValidatedComponent (http://graphub.yodas.com/c94bbd6afadf69c81de90270364906afdea7ff25.js?meteor_js_resource=true:120:10790)
>     at d._updateRenderedComponent (http://graphub.yodas.com/c94bbd6afadf69c81de90270364906afdea7ff25.js?meteor_js_resource=true:120:10206)
>     at d._performComponentUpdate (http://graphub.yodas.com/c94bbd6afadf69c81de90270364906afdea7ff25.js?meteor_js_resource=true:120:10007)
>     at d.updateComponent (http://graphub.yodas.com/c94bbd6afadf69c81de90270364906afdea7ff25.js?meteor_js_resource=true:120:9285)
>     at d.performUpdateIfNecessary (http://graphub.yodas.com/c94bbd6afadf69c81de90270364906afdea7ff25.js?meteor_js_resource=true:120:8814)
>     at Object.performUpdateIfNecessary (http://graphub.yodas.com/c94bbd6afadf69c81de90270364906afdea7ff25.js?meteor_js_resource=true:122:21088)
>     at s (http://graphub.yodas.com/c94bbd6afadf69c81de90270364906afdea7ff25.js?meteor_js_resource=true:123:6877)
>     at r.perform (http://graphub.yodas.com/c94bbd6afadf69c81de90270364906afdea7ff25.js?meteor_js_resource=true:124:8106)

**Screenshot :**

![screenshot from 2016-08-24 06 29 46](https://cloud.githubusercontent.com/assets/3451708/17915029/acfaa808-69c4-11e6-96c3-54427f22909d.png)

**Comment by rantav** [comment]
Sorry for this, I think it happens when there's no such path. Will look into it
